# Generated by Django 3.2.9 on 2021-11-13 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211113_1714'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beers',
            old_name='price',
            new_name='description',
        ),
    ]
