# Generated by Django 3.2.9 on 2021-11-13 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_price_beers_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beers',
            name='description',
            field=models.CharField(max_length=100),
        ),
    ]
