# Generated by Django 3.2.9 on 2021-11-16 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_beers_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beers',
            name='description',
        ),
        migrations.AddField(
            model_name='beers',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
            preserve_default=False,
        ),
    ]
