# Generated by Django 3.2.9 on 2021-11-29 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_beers_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='beers',
            name='reseña',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
