# Generated by Django 3.2.9 on 2021-11-30 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_beers_reseña'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beers',
            old_name='reseña',
            new_name='review',
        ),
    ]
