# Generated by Django 3.2.9 on 2021-12-21 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_reseña_beers_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beers',
            name='review',
            field=models.CharField(max_length=400),
        ),
    ]
